// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FZfb9s2EP8qB24PLSBLSt0Cq/eUZssarAuKxO1LGwyUeJbYUaRGnjy7hYF9iH3CfZLhKMVWEjfpQ5q9",
	"9Mk0qfvxx7vf/fkkSte0zqKlIGafhMfQOhsw/nkh1Rn+2WEg/lc6S2jjUrat0aUk7Wz2ITjLe6GssZG8",
	"+t7jQszEd9kOOutPQ/az986LzWaTCIWh9LplEDET8xrB95dB6TqjwDqCAqGVPqAC52EhtUEFzMPLkmAp",
	"jVaRRCo2iTjq+c2deyV9hQ9LuXBqDbgqEVUAqpFZLnTVeVQQ9EcEoxtNkeex84VWCu3DMtQhelQa4/5C",
	"BcU60gzol+ihdUaX60jvxBJ6K815POmhH4ToQGUXfAYwSAi0e0ak+BtS7dSpo8P+MQ/kSNcRAq50oABF",
	"R6AcjnwKVOsAL+fz19BEfpHqqaNj11n1oLFGNZDdMoysU8FWAxDfsw1u612LnnSf9qVTMXuu4p92DXpd",
	"QtEFbTEEQLYG/jiFM2krjH7oHwX//v0PHOSr1WqUpQk8iTuyozqBaVxbR5MFOyiBZ3FD24WXmSoSeP68",
	"/9/LMYVzxO2/DL3nmy9/08rBwvk+86R1VpfSgImPTsTC+UaSmAltafpEJKLRVjddI2Z5ImjdYn+EFXqO",
	"WYMhyL6ADIeBvLZVdB+7WHvW3LveUbvvL7ZgrviAJTHWS5SG6ps+DiSpiyu0TOSdcH+MAC4vTMQSfdC9",
	"QG4nMyDuI/G2xzixC3eTSdFpo+a62RPyF3wEpBsMJJsWtIWz46PpdPoc3syPxB62laYj1zSaboIdd8ZA",
	"pWNaN5rg/OWhuP29V+3PseHy8Mj5iNIfFvgY3CKGPb5DJHd46RJ+TDUZ+eCm+xhBD567lnHYtEYSQusd",
	"fwuHr09SOF8Hwob3CgzgsZHaQmeHi1FFnf7aFegtEgaQVr23xkkFhTTSlujDj5xJsOio8zjKN6tapy0F",
	"aLpA0AUECdnyFN6cvYLW40Kv0vf8MtJk4gtkmFRuQpc0D1+fiJGDRZ4epDn73LVoZavFTEzTPJ2KRLSS",
	"6qiOrI4C/sjrCmNYWTwxn0+UmIlfkAaNJ1eHhyd5fm9Fb7hhT9XjpqFL5O7WM13zg57m+ecgtxyz0XQT",
	"TaZ3m+xad7R4erfFtv5Hg2d3G9zobWx48AXcro8/m0Q8+xI37Ov3sU90TSP9WszEK73EqMCo6VjaW+9K",
	"3tEBupYlHLu3thWXW5JViBUpZoK4YLTMo1TrW2V0xl/87yqKPL9p6B40xLbTrz/3jGJnHV3G74qAWVn6",
	"moIVtmgV2lJjgEeYVin89OIxSI8MUdayMPhZMY+a1OfU/HbbaL6ansdtfY9jYlPjWVQqSfKbpO+7LPbT",
	"0SAFiCPCPrmwTcTg/esjBM/LBhQuRSI6b8RM1ETtLMviQe0CzX7I81xsLhKxmshWT3bte3kgeHPY4GEn",
	"zpVeElbMr/Nm0o8FDL4bQH4fmvu7XXPf1eeRuC82m/8GAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
