// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FZfb9s2EP8qB24PLSBLTt0Cq/eUZssarAuCxO1LGgyUeJbYUaRGnjy7hYF9iH3CfZLhKMVWYjfpQ5q9",
	"9Mk0qfvxx7vf/fkkClc3zqKlIKafhMfQOBsw/nkl1Tn+2WIg/lc4S2jjUjaN0YUk7Wz2ITjLe6GosJa8",
	"+t7jXEzFd9kWOutOQ/az986L9XqdCIWh8LphEDEVswrBd5dB4VqjwDqCHKGRPqAC52EutUEFzMPLgmAh",
	"jVaRRCrWiTjq+M2ceyN9iY9LOXdqBbgsEFUAqpBZznXZelQQ9EcEo2tNkeex87lWCu3jMtQhelQa4/5C",
	"Bfkq0gzoF+ihcUYXq0jvxBJ6K81FPOmgH4VoT2UbfAYwSBiJ9s+IFH9Dqpw6dXTYPeaRHOlaQsClDhQg",
	"bwmUw4FPgSod4PVsdgZ15Bepnjo6dq1VjxprVD3ZDcPIOhVs1QPxPZvgNt416El3aV84FbPnJv5pW6PX",
	"BeRt0BZDAGRr4I9TOJe2xOiH7lHw79//wMF4uVwOsjSBZ3FHtlQlMIlr62g0Zwcl8CJuaDv3MlN5Ai9f",
	"dv87OaZwgbj5l6H3fPP1b1o6mDvfZZ60zupCGjDx0YmYO19LElOhLU2eiUTU2uq6rcV0nAhaNdgdYYme",
	"Y1ZjCLIrIP1hIK9tGd3HLtaeNXfZOWr7/dUGzOUfsCDGeo3SULXr40CS2rhCy0QuhftjAHB9YSIW6IPu",
	"BHI3mR5xH4l3HcaJnbtdJnmrjZrpek/IX/ERkK4xkKwb0BbOj48mk8lLeDs7EnvYlpqOXF1r2gU7bo2B",
	"Use0rjXBxetDcfd7b9pfYM3l4YnzEaU7zPEpuHkMe3zHLuItL13DD6kmAx/suo8RdO+5WxmHdWMkITTe",
	"8bdweHaSwsUqENa8l2MAj7XUFlrbX4wq6vTXNkdvkTCAtOq9NU4qyKWRtkAffuRMgnlLrcdBvlnVOG0p",
	"QN0GgjYgSMgWp/D2/A00Hud6mb7nl5EmE18gw6h0I7qmeXh2IgYOFuP0IB2zz12DVjZaTMUkHacTkYhG",
	"UhXVkVVRwB95XWIMK4sn5vOJElPxC1Kv8eTm8PBsPH6wotffsKfqcdPQBXJ365iu+EHPu7v3QW44ZoPp",
	"JppM7jfZtu5o8fx+i039jwYv7jfY6W1sePAF3G6PP+tEvPgSN+zr97FPtHUt/UpMxRu9wKjAqOlY2hvv",
	"Ct7RAdqGJRy7t7Yll1uSZYgVKWaCuGK0zKNUqztldM5f/O8qijy/aegBNMS2k68/9wxix5NOH78bAmZl",
	"6VsKVtigVWgLjQGeYFqm8NOrpyA9T1GyqGRu8LNiHjSpz6n53abRfDU9D9v6HsfEpsazqFSS5DdJP3RZ",
	"7KajXgoQR4R9cmGbiMH7t0cInpcNKFyIRLTeiKmoiJpplsWDygWa/jAej8X6KhHLkWz0aNu+FweCN/sN",
	"HnbiXOklYcn8Wm9G3VjA4NsB5Pe+uV9um/u2Pg/EfbVe/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
