// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FbBbtw2EP2VAdtDAijSJhsDtW62W9cGUsOwt7mkPlDirMSUIllyZHsTLNCP6Bf2SwqO5PXau7FzcNxL",
	"TsslNY+Pbx5n+FnUrvPOoqUoys8iYPTORuQ/+1Kd4V89Rkr/amcJLQ+l90bXkrSzxcfobJqLdYudTKMf",
	"A85FKX4obqGLYTUWv4Tgglgul5lQGOugfQIRpZi1CGHYDGrXGwXWEVQIXoaIClyAudQGFSQeQdYEl9Jo",
	"xSRysczEwcBv5tw7GRp8XsqVUwvA6xpRRaAWE8u5bvqACqL+hGB0p4l5HrpQaaXQPi9DHVlRaYy7QgXV",
	"gmlGDJcYwDuj6wXTO7aEwUpzzisD9LMQHancJj8BGCRkouMxmOJvSK1TJ472hsM8k5CuJwS81pEiVD2B",
	"crimKVCrIxzNZqfQMT+meuLo0PVWPWuuUY1kVwyZdS5S1AiU9lkl1wfnMZAern3tFN+eu/gnfYdB11D1",
	"UVuMETBFQ/o4hzNpG2QdhkPBv3//A68n19fXa7c0gzc8I3tqM5jy2Dp6NU8CZbDDE9rOgyxUlcHu7vB/",
	"sGMO54irfwWGkHa++c0bB3MXhpsnrbO6lgYMHzoTcxc6SaIU2tL0jchEp63u+k6Uk0zQwuOwhA2GlLMO",
	"Y5RDARkXIwVtG5YvSaxD8tyHQajb7y9WYK76iDUlrCOUhtpNjSNJ6nmENhH5INyfawA3G2biEkPUg0Ee",
	"JjMibiPxfsA4tnO3yaTqtVEz3W1J+X5aAtIdRpKdB23h7PBgOp3uwu+zA7GFbaPpwHWdpk2ww94YaDRf",
	"604TnB/tiYfPezf+HLtUHl64wCjDYoUvwc057XyOTcR7Kt3Ar1PN1jTYlC8h6FG5ezcOO28kIfjg0rew",
	"d3qcwxl6I2uEK00tLFwfwF1ZiB7r/I+0L2kyjC/jq8a9ohuQvdNjsXZ8Mclf55OkiPNopdeiFNN8kk9F",
	"JryklnNXtGyvT2ncIIueUsu37ViJUvyKNDowu9va30wmT1aSxh221KRU0nWNqfcMTBfpQG+HvbdBrjgW",
	"a28PDpk+HnLbWDni7eMRq+rMATuPB2x0nhT4+iu43X+cLDOx8zUybOvGXMX7rpNhIUrxTl8i12MfXIVc",
	"eH1wdZrREXoP0irurdo2qRiSbCLXi0Uk7MRFQisCSrV40EZn6Yv/3UXM87uHnsBDKXb67V8la7lL75Ax",
	"f3cMnJyl7zlYoUer0NYaI7zAvMnh5/2XIEN648i6lZXBL5p5rYV8yc3vV23gm/l5veluEYZbTnopSiVJ",
	"frf0U5fF4e0yWgG4gW+zS4phjDR/v8Gn16wBhZciE30wohQtkS+LghdaF6n8aTKZiOXF8r8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
