// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Numeric business error code. Range allocation — 10xxx validation, 20xxx auth, 30xxx not-found, 50xxx infra/db, 99xxx internal. See internal/errcode/errcode.go for the canonical list.
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status  HealthStatus `json:"status"`
	Version *string      `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// VersionInfo defines model for VersionInfo.
type VersionInfo struct {
	// BuildTime Build timestamp in RFC3339 UTC
	BuildTime string `json:"buildTime"`

	// GitCommit Full git commit SHA
	GitCommit string `json:"gitCommit"`

	// Version Semver (or git describe) of the build
	Version string `json:"version"`
}
